-- ===== Thesis =====
CREATE TABLE thesis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doi VARCHAR(255),
  title VARCHAR(255) NOT NULL,
  authors VARCHAR(255) NOT NULL
);

-- ===== Tag =====
CREATE TABLE tag (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  full_name VARCHAR(255),
  first_thesis_id BIGINT,
  CONSTRAINT fk_tag_first_thesis FOREIGN KEY (first_thesis_id) REFERENCES thesis (id)
);

-- ===== MLModel =====
CREATE TABLE ml_model (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  full_name VARCHAR(255),
  explain VARCHAR(1000)
);

-- ===== 中間: MLModel-Tag =====
CREATE TABLE mlmodel_tag (
  mlmodel_id BIGINT NOT NULL,
  tag_id     BIGINT NOT NULL,
  PRIMARY KEY (mlmodel_id, tag_id),
  CONSTRAINT fk_mlmodeltag_mlmodel FOREIGN KEY (mlmodel_id) REFERENCES ml_model (id),
  CONSTRAINT fk_mlmodeltag_tag     FOREIGN KEY (tag_id)     REFERENCES tag (id)
);

-- ===== 中間: MLModel-Thesis =====
CREATE TABLE mlmodel_thesis (
  mlmodel_id BIGINT NOT NULL,
  thesis_id  BIGINT NOT NULL,
  PRIMARY KEY (mlmodel_id, thesis_id),
  CONSTRAINT fk_mlmodelthesis_mlmodel FOREIGN KEY (mlmodel_id) REFERENCES ml_model (id),
  CONSTRAINT fk_mlmodelthesis_thesis  FOREIGN KEY (thesis_id)  REFERENCES thesis (id)
);
