# docker-compose.yml （プロジェクトルートに置く）
version: '3.8'
services:
  db:
    image: mysql:8.0       # MySQL公式イメージ
    container_name: aitaxo_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=aitaxo
      - MYSQL_USER=aitaxo_user
      - MYSQL_PASSWORD=pass123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  server:
    build: 
      context: ./server     # serverディレクトリのDockerfileをビルド
    container_name: aitaxo_server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/aitaxo
      - SPRING_DATASOURCE_USERNAME=aitaxo_user
      - SPRING_DATASOURCE_PASSWORD=pass123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  client:
    build:
      context: ./client     # clientディレクトリのDockerfileをビルド
    container_name: aitaxo_client
    ports:
      - "8081:8081"
    depends_on:
      - server

volumes:
  db_data:
